FROM php:5.6-apache

COPY ./app/ /var/www/html/
COPY ./public/ /var/www/html/public/
COPY .env /usr/local/etc/.env

RUN chown -R www-data:www-data /var/www/html

ENV PORT=8000

RUN sed -i "s/Listen 80/Listen ${PORT}/" /etc/apache2/ports.conf && \
    sed -i "s/:80/:${PORT}/" /etc/apache2/sites-available/000-default.conf
RUN echo "DirectoryIndex server.php" > /etc/apache2/conf-enabled/z-custom-directoryindex.conf
RUN sed -i 's/Require all denied/Require all granted/' /etc/apache2/apache2.conf
RUN a2enmod rewrite
RUN service apache2 restart

EXPOSE ${PORT}